### ISSUE TITLE
Code is not included in recipes

### ISSUE THREAD

**Issue by gregburek** [logstash/cookbook#1]
Instead of code being included in the page, the include_code block is visible

example in http://cookbook.logstash.net/recipes/rsyslog-agent/

configure rsyslog
The rsyslog daemon is useful for both taking local syslog messages as well as for pulling logs from files.
To watch files with rsyslog, you want to use the imfile rsyslog module.
For example, let’s say we want to forward local syslog as well as apache and mysql log files to logstash.
{% include_code rsyslog.conf %}

configure logstash
Now, logstash needs to be told to accept syslog input. This is simple enough. Here is an example config that takes syslog and emits it to stdout:
{% include_code logstash.conf %}

**Comment by jordansissel** [comment]
Yeah, that's a bug. I haven't actually implemented the 'include_code' plugin in jekyll yet, hehe

**Comment by gregburek** [comment]
Is this in Octopress or jekyll?  For octopress, I think the fix is something like adding `code_dir: recipes` to config.yaml and prefixing the path names with proper dirs, like `{% include_code rsyslog-agent/logstash.conf %}`. I could be confusing octopress/jekyll configs though...

**Comment by jordansissel** [comment]
I used octopress previously, its include_code plugin doesn't work the way I want (I want code relative to the directory the page is in, not relative to a single path in the project), and I had patched it. Also had to disable the code highlighting it did because of rubypython problems on my laptop. 

I started from scratch a few days ago after fiddling around a bit, and the include_code plugin hasn't made its way back in just yet.

The site right now uses jekyll :)

**Comment by gregburek** [comment]
Ok cool.  The code is, after all, accessible. Thanks for putting this cookbook up. Logstash seems like a really awesome project.

**Comment by jordansissel** [comment]
Woo! Yeah the code's there, sorry about the funky template problems right now :)

**Comment by jordansissel** [comment]
Fixed!

I ended up using javascript because it's probably not possible to make jekyll load plugins on github pages  Works well :)

**Comment by gregburek** [comment]
Awesome! Thanks!
